name: Build macOS executable

on:
  workflow_dispatch:
  push:
    # Support both main and master branches in case default branch differs
    branches: [ main, master ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          brew update || true
          brew install imagemagick || true

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pillow

      - name: Convert icon.ico -> icon.png using Pillow (more reliable than ImageMagick)
        run: |
          python - <<'PY'
          from PIL import Image
          import os
          if os.path.exists('icon.ico'):
              try:
                  img = Image.open('icon.ico')
                  # Save a reasonably large PNG for icon generation
                  img.save('icon.png')
                  print('Saved icon.png')
              except Exception as e:
                  print('Failed to convert icon.ico:', e)
          else:
              print('icon.ico not found; skipping conversion')
          PY

      - name: Generate icon.icns if icon.png exists
        run: |
          if [ -f icon.png ]; then
            mkdir -p icon.iconset
            sips -z 16 16 icon.png --out icon.iconset/icon_16x16.png
            sips -z 32 32 icon.png --out icon.iconset/icon_16x16@2x.png
            sips -z 32 32 icon.png --out icon.iconset/icon_32x32.png
            sips -z 64 64 icon.png --out icon.iconset/icon_32x32@2x.png
            sips -z 128 128 icon.png --out icon.iconset/icon_128x128.png
            sips -z 256 256 icon.png --out icon.iconset/icon_128x128@2x.png
            sips -z 256 256 icon.png --out icon.iconset/icon_256x256.png
            sips -z 512 512 icon.png --out icon.iconset/icon_256x256@2x.png
            sips -z 512 512 icon.png --out icon.iconset/icon_512x512.png
            sips -z 1024 1024 icon.png --out icon.iconset/icon_512x512@2x.png
            iconutil -c icns icon.iconset -o icon.icns || true
          else
            echo 'icon.png not found; skipping icon.icns generation'
          fi

      - name: Build macOS .app with PyInstaller
        run: |
          # Build an application bundle (.app) instead of a single-file executable.
          # This prevents Terminal from opening when users double-click the app.
          if [ -f icon.icns ]; then
            ICON_ARG="--icon icon.icns"
          else
            ICON_ARG=""
          fi
          python -m PyInstaller --windowed --name "PasswordLocker" $ICON_ARG main.py

      - name: Package .app into zip
        run: |
          APPNAME="PasswordLocker.app"
          if [ -d "dist/$APPNAME" ]; then
            ZIPNAME="PasswordLocker-mac.zip"
            cd dist
            zip -r "$ZIPNAME" "$APPNAME"
            mv "$ZIPNAME" .. || true
            cd ..
            mkdir -p release
            mv dist/PasswordLocker-mac.zip release/ || true
            echo "Packaged dist/$APPNAME -> release/PasswordLocker-mac.zip"
          else
            echo "Warning: dist/$APPNAME not found; listing dist contents:";
            ls -la dist || true
          fi

      - name: Upload mac .app zip artifact (with fallbacks)
        uses: actions/upload-artifact@v4
        with:
          name: mac-executable
          # Try multiple possible locations / patterns so upload doesn't fail if zip ended up elsewhere
          path: |
            release/PasswordLocker-mac.zip
            dist/PasswordLocker-mac.zip
            dist/PasswordLocker.app
            dist/*.zip
            release/*.zip
